<?php

namespace AppBundle\Repository;

/**
 * ComplexeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplexeRepository extends \Doctrine\ORM\EntityRepository
{
}
