<?php

namespace AppBundle\Repository;

/**
 * ComplexeGerantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplexeGerantRepository extends \Doctrine\ORM\EntityRepository
{
}
