<?php

namespace AppBundle\Repository;

/**
 * HistoriqueNavigationComplexeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueNavigationComplexeRepository extends \Doctrine\ORM\EntityRepository
{
}
