<?php

namespace AppBundle\Repository;

/**
 * PlageHoraireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlageHoraireRepository extends \Doctrine\ORM\EntityRepository
{
}
