<?php

namespace AppBundle\Repository;

/**
 * PlageHoraireStatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlageHoraireStatutRepository extends \Doctrine\ORM\EntityRepository
{
}
