<?php

namespace AppBundle\Repository;

/**
 * PlanningCommissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanningCommissionRepository extends \Doctrine\ORM\EntityRepository
{
}
