<?php

namespace AppBundle\Repository;

/**
 * PlanningTarifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanningTarifRepository extends \Doctrine\ORM\EntityRepository
{
}
