<?php

namespace AppBundle\Repository;

/**
 * TerrainTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerrainTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
