<?php

namespace AppBundle\Repository;

/**
 * TypeEchangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEchangeRepository extends \Doctrine\ORM\EntityRepository
{
}
