<?php

namespace AppBundle\Repository;

/**
 * UtilisateurTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
