<?php

namespace AppBundle\Repository;

/**
 * UtilisateurApiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurApiRepository extends \Doctrine\ORM\EntityRepository
{
}
